name: build-and-update

on:
  schedule:
    # Chạy tự động lúc 00 phút mỗi giờ (1 tiếng / lần)
    - cron: '0 * * * *'
  workflow_dispatch: # Nút bấm chạy thủ công trên GitHub

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push M3U file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update playlist M3U" && git push)
          
